### ISSUE TITLE
ERROR ECS fargate task does not start.

### ISSUE THREAD

**Issue by chrisXar** [awslabs/harmonix#105]
## Description

I'm trying to install Harmonix, but the installation did not finish succesfully, the ECS task definition never has a task running. The stopped tasks shows the message:

ForwardedError [TypeError]: Module 'gitlab' for plugin 'scaffolder' startup failed; caused by TypeError: Invalid type in config for key 'integrations.github[0].host' in 'app-config.aws-production.yaml', got empty-string, wanted string

I don have any variable of GitHUB in my config/.env file, so I don't know why it still wanted a value for GitHub integration.

## Versions

- OPA plugin versions [Required]:
root@C11-PNOPH6BSJXD:/harmonix/backstage# yarn list --cwd backstage --pattern aws-apps
yarn list v1.22.22
├─ @aws/backstage-plugin-catalog-backend-module-aws-apps-entities-processor@0.3.4
├─ @aws/plugin-aws-apps-backend-for-backstage@0.3.4
├─ @aws/plugin-aws-apps-common-for-backstage@0.3.4
├─ @aws/plugin-aws-apps-demo-for-backstage@0.3.3
├─ @aws/plugin-aws-apps-for-backstage@0.3.5
└─ @aws/plugin-scaffolder-backend-aws-apps-for-backstage@0.3.4
Done in 1.28s.

## Reproduction Code [Required]

I'm ussing the last release from your github code.

I install the prerequisites:
root@C11-PNOPH6BSJXD:/harmonix/backstage#  node -v
    yarn -v
    aws --version
    cdk --version
    jq --version
    docker --version
    git --version
    python3 --version
v18.20.4
1.22.22
aws-cli/2.17.40 Python/3.11.9 Linux/5.15.146.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.22
2.154.1 (build febce9d)
jq-1.6
Docker version 27.2.0, build 3ab4256
git version 2.34.1
Python 3.10.12

Then, I run Make install

## Expected behavior

The ECS taks starts good, and the final state Running

## Actual behavior

The tasks are stopped

### Terminal Output Screenshot(s)
[install_20240829-1222.log](https://github.com/user-attachments/files/16802909/install_20240829-1222.log)
[app-config.aws-production.txt](https://github.com/user-attachments/files/16802933/app-config.aws-production.txt)

**Comment by chrisXar** [comment]
I changed .json to .txt because it does not let me up json file

**Comment by chrisXar** [comment]
[log-events-viewer-result.csv](https://github.com/user-attachments/files/16802979/log-events-viewer-result.csv)
I attached the log of ECS task

**Comment by z-sourcecode** [comment]
Hi @chrisXar thanks for reaching out, 
Please make sure you use the latest sample.env - it has a default value of "github.com"
https://github.com/awslabs/harmonix/blob/558792058098e38f57dccbb9e19063f0d9e57a51/config/sample.env#L101

You may also comment out github configurations(integrations.github) if you don't need it and use gitlab.

**Comment by chrisXar** [comment]
Hi @z-sourcecode i'm very sure i'm using the latest version of sample.env because i cloned the repository a few minutes earlier to do this installation. when I copied the sample.env to config/.env I comment out the GITHUB_HOSTNAME variable and GITHUB-SECRET-NAME variable (you can see in install log file that it skipped the GITHUB Secret creation), is there something else that I have to do for skip all GITHUB configuratión? If yes, please give the step by step to fulfill this and fix it.

**Comment by z-sourcecode** [comment]
Can you please try to **not** comment out the GITHUB_HOSTNAME  and GITHUB-SECRET-NAME.
Even if you may not actually use them in your app-config.aws-production.yaml.
Please let me know if this works?

**Comment by z-sourcecode** [comment]
Closing this ticket as it resolved.
